service: tokenizepaycard

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1

plugins:
  - serverless-offline

functions:
  save:
    handler: dist/infrastructure/pay-card.handler.save
    events:
      - http:
        path: /
        method: post
  get:
    handler: dist/infrastructure/pay-card.handler.get
    events:
      - http:
        path: /get/{:id}
        method: get